version: '3'

services:
  web:
    build:
      context: ../../../
      dockerfile: ./deployments/docker/localdemo/Dockerfile
    restart: on-failure
    ports:
      - "80:5678"
    depends_on:
      - "database"
    networks:
      - "kapibara-testnet"
    container_name: "kapibara-apigateway"
  database:
    image: "mysql:latest"
    container_name: "db-mysql0"
    build:
      context: .
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test_kapibara_root_pwd"
      MYSQL_DATABASE: "auth_test_db0"
      MYSQL_USER: "test_kapibara"
      MYSQL_PASSWORD: "test_kapibara_pwd"
    networks:
      - "kapibara-testnet"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

networks:
  kapibara-testnet:
    driver: "bridge"
