apiVersion: v1
kind: Service
metadata:
  name: kapibara-apigateway-svc
  namespace: web-general
spec:
  selector:
    app: kapibara-apigateway
  ports:
    - protocol: TCP
      nodePort: 30009
      port: 80      
      targetPort: 80
  type: NodePort
