apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapibara-apigateway
  namespace: web-general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapibara-apigateway
      feature: worker
  template:
    metadata:
      labels:
        app: kapibara-apigateway
        feature: worker
    spec:
      containers:
      - name: kapibara-apigateway
        image: <DOCKER_HUB_REPO>/<KapibaraApiGatewayImage>
        imagePullPolicy: Never
        volumeMounts:
        - name: tls-secret
          mountPath: "/etc/tls"
        - name: nfs-volume
          mountPath: /mnt/nfs/mikanani
          readOnly: false
        envFrom:
        - secretRef:
            name: kapibara-apigateway-config
        command: ["./kapibara-apigateway_exe", "-tls"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
      - name: tls-secret
        secret:
          secretName: kapibara-tls
      - name: nfs-volume
        nfs:
          server: <NFS_SERVER_IP>
          path: <MIKANANI_NFS_PATH>
          readOnly: false
