apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapibara-apigateway
  namespace: web-general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapibara-apigateway
      feature: worker
  template:
    metadata:
      labels:
        app: kapibara-apigateway
        feature: worker
    spec:
      containers:
      - name: kapibara-apigateway
        image: <DOCKER_HUB_REPO>/<KapibaraApiGatewayImage>
        imagePullPolicy: Never
        volumeMounts:
        - name: tls-secret
          mountPath: "/etc/tls"
        envFrom:
        - secretRef:
            name: kapibara-apigateway-config
        command: ["./kapibara-apigateway_exe", "-tls"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: tls-secret
        secret:
          secretName: kapibara-tls
