name: Kapibara-Apigateway Deployment
run-name: Deploy ${{ github.event.inputs.module }}-${{ github.event.inputs.deploymode }}

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: module
        options:
          - Kapibara-apigateway
        required: true
      deploymode:
        type: choice
        description: dev/prod
        options:
            - dev
            - prod
        required: true
jobs:

  build-docker-image-and-deploy-to-k8s:
    runs-on: self-hosted

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        image_name=`echo ${{ github.event.inputs.module }} | awk '{print tolower($1)}'`
        docker build -f ./deployments/docker/deployimage/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}/$image_name:latest .
        export KUBECONFIG=$HOME/.kube/config
        docker save ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}/$image_name:latest | k3s ctr images import -
        docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}/$image_name:latest
      
    - name: Deploy on Kubernetes
      run: |
        image_name=`echo ${{ github.event.inputs.module }} | awk '{print tolower($1)}'`
        image="${image_name}:latest"
        repo="${{ secrets.DOCKER_HUB_USERNAME }}\/${{ secrets.DOCKER_HUB_REPO }}"

        case "${{ github.event.inputs.deploymode }}" in
        "dev")
        echo "Deploy dev mode..."
        sed -i "s/<DOCKER_HUB_REPO>/${repo}/g" ./deployments/kubernetes/dev/worker.yaml
        sed -i "s/<KapibaraApiGatewayImage>/${image}/g" ./deployments/kubernetes/dev/worker.yaml

        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/dev/worker.yaml
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/dev/service.yaml
        ;;
        "prod")
        echo "Deploy prod mode..."
        sed -i "s/<DOCKER_HUB_REPO>/${repo}/g" ./deployments/kubernetes/prod/worker.yaml
        sed -i "s/<KapibaraApiGatewayImage>/${image}/g" ./deployments/kubernetes/prod/worker.yaml

        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/prod/worker.yaml
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/prod/service.yaml
        ;;
        esac
