name: Kapibara-Apigateway Deployment
run-name: Deploy ${{ github.event.inputs.module }}-${{ github.event.inputs.deploymode }}

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: module
        options:
          - Kapibara-apigateway
        required: true
      deploymode:
        type: choice
        description: dev/prod
        options:
            - dev
            - prod
        required: true
jobs:

  build-docker-image-and-deploy-to-k8s:
    runs-on: self-hosted

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        image_name=`echo ${{ github.event.inputs.module }} | awk '{print tolower($1)}'`
        docker build -f ./deployments/docker/mikanani/Dockerfile -t ${{ secrets.HARBOR_HUB }}/${{ secrets.HARBOR_REPO }}/$image_name:latest .
        export KUBECONFIG=$HOME/.kube/config
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S docker login ${{ secrets.HARBOR_HUB }} -u ${{ secrets.HARBOR_USER }} -p ${{ secrets.HARBOR_PWD }} 
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S docker push ${{ secrets.HARBOR_HUB }}/${{ secrets.HARBOR_REPO }}/$image_name:latest
        docker rmi ${{ secrets.HARBOR_HUB }}/${{ secrets.HARBOR_REPO }}/$image_name:latest
      
    - name: Deploy on Kubernetes
      run: |
        image_name=`echo ${{ github.event.inputs.module }} | awk '{print tolower($1)}'`
        image="${image_name}:latest"
        repo="${{ secrets.HARBOR_REPO }}"
        nfsip="${{ secrets.NFS_SERVER_IP }}"
        mikananinfspath="${{ secrets.MIKANANI_NFS_PATH }}"

        case "${{ github.event.inputs.deploymode }}" in
        "dev")
        echo "Deploy dev mode..."
        sed -i "s|<HARBOR_HUB_REPO>|${repo}|g" ./deployments/kubernetes/dev/worker.yaml
        sed -i "s|<KapibaraApiGatewayImage>|${image}|g" ./deployments/kubernetes/dev/worker.yaml

        sed -i "s|<NFS_SERVER_IP>|${nfsip}|g" ./deployments/kubernetes/dev/worker.yaml
        sed -i "s|<MIKANANI_NFS_PATH>|${mikananinfspath}|g" ./deployments/kubernetes/dev/worker.yaml

        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/dev/worker.yaml
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/dev/service.yaml
        ;;
        "prod")
        echo "Deploy prod mode..."
        sed -i "s/<HARBOR_HUB_REPO>/${repo}/g" ./deployments/kubernetes/prod/worker.yaml
        sed -i "s/<KapibaraApiGatewayImage>/${image}/g" ./deployments/kubernetes/prod/worker.yaml

        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/prod/worker.yaml
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/prod/service.yaml
        ;;
        esac
